FROM python:3.12.5

# Install APT dependencies
RUN apt-get update
RUN apt-get install git wget gcc ubuntu-drivers-common nvidia-driver-550 -y 

# Install CUDA
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cuda

# Set working directory
WORKDIR /app

# Clone the ComfyUI repository
RUN git clone https://github.com/comfyanonymous/ComfyUI.git
WORKDIR /app/ComfyUI

# Install Python dependencies
RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# # Download the flux schnell FP8 checkpoint if not already downloaded
# RUN mkdir -p ./models/checkpoints && \
#     [ -f ./models/checkpoints/flux1-schnell-fp8.safetensors ] || \
#     wget https://huggingface.co/Comfy-Org/flux1-schnell/resolve/main/flux1-schnell-fp8.safetensors -P ./models/checkpoints/

# # Download the VAE model if not already downloaded
# RUN mkdir -p ./models/vae && \
#     [ -f ./models/vae/ae.safetensors ] || \
#     wget https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/ae.safetensors -P ./models/vae/

# # Download the UNet model if not already downloaded
# RUN mkdir -p ./models/unet && \
#     [ -f ./models/unet/flux1-schnell.safetensors ] || \
#     wget https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/flux1-schnell.safetensors -P ./models/unet/

CMD [ "python3", "./main.py" ]